-----------
## In this notebook:
* Import and clean up df
* Take 'precip' difference
* Create precip and no precip DFs
-----------

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

## Load Data

In [2]:
df = pd.read_parquet('/tf/NYSM/mesonet_parquet/201508-202012.parquet')

In [3]:
df.columns

Index(['index', 'station', 'time_5M', 'lat', 'lon', 'elev', 'tair', 'ta9m',
       'tslo', 'relh', 'srad', 'pres', 'wspd_sonic', 'wmax_sonic',
       'wssd_sonic', 'wdir_sonic', 'wdsd_sonic', 'wspd_prop', 'wmax_prop',
       'wssd_prop', 'wdir_prop', 'wdsd_prop', 'wspd_merge', 'wmax_merge',
       'wssd_merge', 'wdir_merge', 'wdsd_merge', 'precip', 'precip_total',
       'precip_max_intensity', 'SRAD1HR', 'ts05', 'ts25', 'ts50', 'sm05',
       'sm25', 'sm50', 'frozen05', 'frozen25', 'frozen50', 'snow_depth',
       'filedate', 'tair_qa', 'relh_qa', 'tslo_qa', 'ta9m_qa', 'srad_qa',
       'wspd_sonic_qa', 'wmax_sonic_qa', 'wssd_sonic_qa', 'wdir_sonic_qa',
       'wdsd_sonic_qa', 'wvec_sonic_qa', 'count_sonic_qa', 'wspd_prop_qa',
       'wmax_prop_qa', 'wssd_prop_qa', 'wdir_prop_qa', 'wdsd_prop_qa',
       'wvec_prop_qa', 'pres_qa', 'precip_qa', 'precip_maxint_qa',
       'precip_sumint_qa', 'precip_rt_nrt_qa', 'precip_nrt_qa',
       'precip_total_qa', 'sr50a_dist_qa', 'ts05_qa', 'er05_qa', 'ert05_qa',
       'lsm05_qa', 'ts25_qa', 'er25_qa', 'ert25_qa', 'lsm25_qa', 'ts50_qa',
       'er50_qa', 'ert50_qa', 'lsm50_qa', 'batv_qa', 'flsv_qa', 'stnm',
       'stid'],
      dtype='object')

In [4]:
# drop unecessary variables

drop_vars = ['lat', 'lon', 'elev',
       'tslo', 'relh', 'srad', 'pres', 'wspd_sonic', 'wmax_sonic',
       'wssd_sonic', 'wdir_sonic', 'wdsd_sonic', 'wspd_prop', 'wmax_prop',
       'wssd_prop', 'wdir_prop', 'wdsd_prop', 'wspd_merge', 'wmax_merge',
       'wssd_merge', 'wdir_merge', 'wdsd_merge', 'SRAD1HR', 'ts05', 'ts25', 'ts50', 'sm05',
       'sm25', 'sm50', 'frozen05', 'frozen25', 'frozen50',
       'filedate', 'tair_qa', 'relh_qa', 'tslo_qa', 'ta9m_qa', 'srad_qa',
       'wspd_sonic_qa', 'wmax_sonic_qa', 'wssd_sonic_qa', 'wdir_sonic_qa',
       'wdsd_sonic_qa', 'wvec_sonic_qa', 'count_sonic_qa', 'wspd_prop_qa',
       'wmax_prop_qa', 'wssd_prop_qa', 'wdir_prop_qa', 'wdsd_prop_qa',
       'wvec_prop_qa', 'pres_qa', 'precip_qa', 'precip_maxint_qa',
       'precip_sumint_qa', 'precip_rt_nrt_qa', 'precip_nrt_qa',
       'precip_total_qa', 'sr50a_dist_qa', 'ts05_qa', 'er05_qa', 'ert05_qa',
       'lsm05_qa', 'ts25_qa', 'er25_qa', 'ert25_qa', 'lsm25_qa', 'ts50_qa',
       'er50_qa', 'ert50_qa', 'lsm50_qa', 'batv_qa', 'flsv_qa', 'stnm',
       'stid']

df = df.drop(drop_vars,axis=1)

## Precip vs No Precip

In [5]:
# use precip values and corresponding dates
values = np.array(df['precip'])
dates = np.array(df['time_5M'])

# differentiate to determine where there is/isn't precip
values_diffs = np.diff(values)
values_diff = np.append([-1], values_diffs)

# define where there is precipitation
precip = np.where(values_diff > 0)
precip_dates = dates[precip]

# define where there is no precipitation
no_precip = np.where(values_diff == 0)
no_precip_dates = dates[no_precip]

In [6]:
print(np.array(precip).shape)
print(np.array(no_precip).shape)

(1, 3466255)
(1, 51950185)

In [7]:
# add differences to df
df['precip_diff'] = values_diff

## Convert to DFs

In [8]:
# create a preicp df
precip_df = df[(df['precip_diff'] > 0)]

# change index
precip_df['index'] = list(range(0,len(precip_df)))

In [10]:
precip_df[0:30]

,index,station,time_5M,tair,ta9m,precip,precip_total,precip_max_intensity,snow_depth,precip_diff
411,0,b'SCHU',2015-08-11 10:15:00,NaN,NaN,0.054,0.000,0.000,NaN,0.054
412,1,b'SCHU',2015-08-11 10:20:00,NaN,NaN,0.196,0.054,0.000,NaN,0.142
413,2,b'SCHU',2015-08-11 10:25:00,NaN,NaN,0.441,0.196,0.000,NaN,0.245
414,3,b'SCHU',2015-08-11 10:30:00,NaN,NaN,0.702,0.441,0.000,NaN,0.261
415,4,b'SCHU',2015-08-11 10:35:00,NaN,NaN,0.822,0.702,0.000,NaN,0.120
416,5,b'SCHU',2015-08-11 10:40:00,NaN,NaN,0.978,0.822,0.000,NaN,0.156
417,6,b'SCHU',2015-08-11 10:45:00,NaN,NaN,1.260,0.978,0.000,NaN,0.282
418,7,b'SCHU',2015-08-11 10:50:00,NaN,NaN,1.560,1.260,0.000,NaN,0.300
419,8,b'SCHU',2015-08-11 10:55:00,NaN,NaN,1.773,1.560,0.000,NaN,0.213
420,9,b'SCHU',2015-08-11 11:00:00,NaN,NaN,2.161,1.773,0.000,NaN,0.388
421,10,b'SCHU',2015-08-11 11:05:00,NaN,NaN,2.352,2.161,0.000,NaN,0.191
422,11,b'SCHU',2015-08-11 11:10:00,NaN,NaN,2.447,2.352,0.000,NaN,0.095
424,12,b'SCHU',2015-08-11 11:20:00,NaN,NaN,2.655,2.447,0.000,NaN,0.208
425,13,b'SCHU',2015-08-11 11:25:00,NaN,NaN,2.721,2.655,0.000,NaN,0.066
426,14,b'SCHU',2015-08-11 11:30:00,NaN,NaN,2.877,2.721,0.000,NaN,0.156
427,15,b'SCHU',2015-08-11 11:35:00,NaN,NaN,3.071,2.877,0.000,NaN,0.194
428,16,b'SCHU',2015-08-11 11:40:00,NaN,NaN,3.259,3.071,0.000,NaN,0.188
429,17,b'SCHU',2015-08-11 11:45:00,18.566290,18.592960,3.526,3.259,0.000,NaN,0.267
430,18,b'SCHU',2015-08-11 11:50:00,18.610609,18.620770,3.790,3.526,0.000,NaN,0.264
431,19,b'SCHU',2015-08-11 11:55:00,18.358061,18.564310,4.055,3.790,0.000,NaN,0.265
432,20,b'SCHU',2015-08-11 12:00:00,18.345570,18.479540,4.269,4.055,0.000,NaN,0.214
433,21,b'SCHU',2015-08-11 12:05:00,18.422171,18.409050,4.402,4.269,0.000,NaN,0.133
434,22,b'SCHU',2015-08-11 12:10:00,18.405430,18.412741,4.748,4.402,0.000,NaN,0.346
435,23,b'SCHU',2015-08-11 12:15:00,18.430910,18.439140,5.344,4.748,0.231,NaN,0.596
436,24,b'SCHU',2015-08-11 12:20:00,18.371201,18.322069,6.251,5.344,0.410,NaN,0.907
437,25,b'SCHU',2015-08-11 12:25:00,18.324381,18.396090,6.542,6.251,0.000,NaN,0.291
438,26,b'SCHU',2015-08-11 12:30:00,18.437889,18.478060,6.748,6.542,0.000,NaN,0.206
439,27,b'SCHU',2015-08-11 12:35:00,18.508169,18.465931,6.969,6.748,0.000,NaN,0.221
440,28,b'SCHU',2015-08-11 12:40:00,18.553379,18.478230,7.155,6.969,0.000,NaN,0.186
441,29,b'SCHU',2015-08-11 12:45:00,18.582840,18.518351,7.497,7.155,0.000,NaN,0.342

In [13]:
# save precip df
precip_df.to_pickle("precip_df.pkl")

In [11]:
# create a no_precip df
no_precip_df = df[(df['precip_diff'] == 0)]

# change index
no_precip_df['index'] = list(range(0,len(no_precip_df)))

In [12]:
no_precip_df[0:30]

,index,station,time_5M,tair,ta9m,precip,precip_total,precip_max_intensity,snow_depth,precip_diff
291,0,b'SCHU',2015-08-11 00:15:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
292,1,b'SCHU',2015-08-11 00:20:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
293,2,b'SCHU',2015-08-11 00:25:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
294,3,b'SCHU',2015-08-11 00:30:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
295,4,b'SCHU',2015-08-11 00:35:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
296,5,b'SCHU',2015-08-11 00:40:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
297,6,b'SCHU',2015-08-11 00:45:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
298,7,b'SCHU',2015-08-11 00:50:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
299,8,b'SCHU',2015-08-11 00:55:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
300,9,b'SCHU',2015-08-11 01:00:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
301,10,b'SCHU',2015-08-11 01:05:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
302,11,b'SCHU',2015-08-11 01:10:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
303,12,b'SCHU',2015-08-11 01:15:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
304,13,b'SCHU',2015-08-11 01:20:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
305,14,b'SCHU',2015-08-11 01:25:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
306,15,b'SCHU',2015-08-11 01:30:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
307,16,b'SCHU',2015-08-11 01:35:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
308,17,b'SCHU',2015-08-11 01:40:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
309,18,b'SCHU',2015-08-11 01:45:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
310,19,b'SCHU',2015-08-11 01:50:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
311,20,b'SCHU',2015-08-11 01:55:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
312,21,b'SCHU',2015-08-11 02:00:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
313,22,b'SCHU',2015-08-11 02:05:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
314,23,b'SCHU',2015-08-11 02:10:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
315,24,b'SCHU',2015-08-11 02:15:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
316,25,b'SCHU',2015-08-11 02:20:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
317,26,b'SCHU',2015-08-11 02:25:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
318,27,b'SCHU',2015-08-11 02:30:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
319,28,b'SCHU',2015-08-11 02:35:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0
320,29,b'SCHU',2015-08-11 02:40:00,NaN,NaN,0.0,0.0,0.0,NaN,0.0

In [14]:
# save no precip df
no_precip_df.to_pickle("no_precip_df.pkl")